---
title: "03-d2H-water-C16.0-phytol"
author: "Antonia_Klatt"
date: "2024-08-01"
output: html_document
---

```{r}
knitr::opts_chunk$set(echo = TRUE)

#loading packages

library(readr)
library(here)
library(ggplot2)
library(reshape2)
library(cowplot)
Sys.setlocale("LC_ALL", "English")

#import d2H data

d2H_H2O_lipids <- read.csv(here("01_Data","d2H_H2O_lipids_ROT19.csv"), header = TRUE , sep = ";" , stringsAsFactors = FALSE, na.strings = "#NV")


#note: data frame includes two different depths: surface water (A) and chlorophyll maximum depth (B)


#separating surface water (surface) and chlorophyll maximum depth (chlorMax)

d2H_H2O_lipids_surface <- d2H_H2O_lipids[1:27,]

d2H_H2O_lipids_chlorMax <- d2H_H2O_lipids[28:54,]


#Checking correlations between d2H water values and d2H lipid values (R2 values)

## both depths

summary(lm(H2O_Avg.d2H_VSMOW~C16.0_Avg.d2H_VSMOW, data=d2H_H2O_lipids)) 

summary(lm(H2O_Avg.d2H_VSMOW~phytol_Avg.d2H_VSMOW, data=d2H_H2O_lipids))


## surface water

summary(lm(H2O_Avg.d2H_VSMOW~C16.0_Avg.d2H_VSMOW, data=d2H_H2O_lipids_surface)) 

summary(lm(H2O_Avg.d2H_VSMOW~phytol_Avg.d2H_VSMOW, data=d2H_H2O_lipids_surface))


## chlorophyll maximum depth

summary(lm(H2O_Avg.d2H_VSMOW~C16.0_Avg.d2H_VSMOW, data=d2H_H2O_lipids_chlorMax)) 

summary(lm(H2O_Avg.d2H_VSMOW~phytol_Avg.d2H_VSMOW, data=d2H_H2O_lipids_chlorMax))


#setting sampling dates

d2H_datesA <- c("2019-01-30", "2019-02-13", "2019-02-27", "2019-03-13" , "2019-03-27", "2019-04-10" ,"2019-04-24","2019-05-08",
                "2019-05-22", "2019-06-04" ,"2019-06-19", "2019-07-17" , "2019-07-29", "2019-08-14","2019-08-28", "2019-09-11",
                "2019-09-25", "2019-10-09", "2019-10-23", "2019-11-06", "2019-11-20", "2019-12-04", "2019-12-18","2020-01-07",
                "2020-01-21", "2020-02-06", "2020-02-18")

rownames(d2H_H2O_lipids_surface) <- d2H_datesA

d2H_H2O_lipids_surface$date <- as.Date(rownames(d2H_H2O_lipids_surface), "%Y-%m-%d")



d2H_datesB <- c("2019-01-30", "2019-02-13","2019-02-27",  "2019-03-13" , "2019-03-27", "2019-04-10" ,"2019-04-24","2019-05-08",
                "2019-05-22", "2019-06-04" ,"2019-06-19", "2019-07-17" , "2019-07-29", "2019-08-14","2019-08-28", "2019-09-11",
                "2019-09-25", "2019-10-09", "2019-10-23", "2019-11-06", "2019-11-20", "2019-12-04", "2019-12-18", "2020-01-07",
                "2020-01-21", "2020-02-06", "2020-02-18")                              

rownames(d2H_H2O_lipids_chlorMax) <- d2H_datesB

d2H_H2O_lipids_chlorMax$date <- as.Date(rownames(d2H_H2O_lipids_chlorMax), "%Y-%m-%d")


#reshape data frames

## choosing d2H values and standard deviations (SD) separately for plotting

d2H_H2O_A <- melt(subset(d2H_H2O_lipids_surface, select= c(date, H2O_Avg.d2H_VSMOW)),id.var="date")
d2H.SD_H2O_A <- melt(subset(d2H_H2O_lipids_surface, select= c(date, H2O_SD.d2H_VSMOW)),id.var="date")

d2H_C16.0_A <- melt(subset(d2H_H2O_lipids_surface, select= c(date, C16.0_Avg.d2H_VSMOW)),id.var="date")
d2H.SD_C16.0_A <- melt(subset(d2H_H2O_lipids_surface, select= c(date, C16.0_SD.d2H_VSMOW)),id.var="date")

d2H_phytol_A <- melt(subset(d2H_H2O_lipids_surface, select= c(date, phytol_Avg.d2H_VSMOW)),id.var="date")
d2H.SD_phytol_A <- melt(subset(d2H_H2O_lipids_surface, select= c(date, phytol_SD.d2H_VSMOW)),id.var="date")

d2H_brassicasterol_A <- melt(subset(d2H_H2O_lipids_surface, select= c(date, brassicasterol_Avg.d2H_VSMOW)),id.var="date")
d2H.SD_brassicasterol_A <- melt(subset(d2H_H2O_lipids_surface, select= c(date, brassicasterol_SD.d2H_VSMOW)),id.var="date")

d2H_ergosterol_A <- melt(subset(d2H_H2O_lipids_surface, select= c(date,ergosterol_Avg.d2H_VSMOW)),id.var="date")
d2H.SD_ergosterol_A <- melt(subset(d2H_H2O_lipids_surface, select= c(date,ergosterol_SD.d2H_VSMOW)),id.var="date")

d2H_sitosterol_A <- melt(subset(d2H_H2O_lipids_surface, select= c(date,sitosterol_Avg.d2H_VSMOW)),id.var="date")
d2H.SD_sitosterol_A <- melt(subset(d2H_H2O_lipids_surface, select= c(date,sitosterol_SD.d2H_VSMOW)),id.var="date")

d2H_stigmasterol_A <- melt(subset(d2H_H2O_lipids_surface, select= c(date,stigmasterol_Avg.d2H_VSMOW)),id.var="date")
d2H.SD_stigmasterol_A <- melt(subset(d2H_H2O_lipids_surface, select= c(date,stigmasterol_SD.d2H_VSMOW)),id.var="date")


d2H_H2O_B <- melt(subset(d2H_H2O_lipids_chlorMax, select= c(date, H2O_Avg.d2H_VSMOW)),id.var="date")
d2H.SD_H2O_B <- melt(subset(d2H_H2O_lipids_chlorMax, select= c(date, H2O_SD.d2H_VSMOW)),id.var="date")

d2H_C16.0_B <- melt(subset(d2H_H2O_lipids_chlorMax, select= c(date, C16.0_Avg.d2H_VSMOW)),id.var="date")
d2H.SD_C16.0_B <- melt(subset(d2H_H2O_lipids_chlorMax, select= c(date, C16.0_SD.d2H_VSMOW)),id.var="date")

d2H_phytol_B <- melt(subset(d2H_H2O_lipids_chlorMax, select= c(date, phytol_Avg.d2H_VSMOW)),id.var="date")
d2H.SD_phytol_B <- melt(subset(d2H_H2O_lipids_chlorMax, select= c(date, phytol_SD.d2H_VSMOW)),id.var="date")

d2H_brassicasterol_B <- melt(subset(d2H_H2O_lipids_chlorMax, select= c(date, brassicasterol_Avg.d2H_VSMOW)),id.var="date")
d2H.SD_brassicasterol_B <- melt(subset(d2H_H2O_lipids_chlorMax, select= c(date, brassicasterol_SD.d2H_VSMOW)),id.var="date")

d2H_ergosterol_B <- melt(subset(d2H_H2O_lipids_chlorMax, select= c(date,ergosterol_Avg.d2H_VSMOW)),id.var="date")
d2H.SD_ergosterol_B <- melt(subset(d2H_H2O_lipids_chlorMax, select= c(date,ergosterol_SD.d2H_VSMOW)),id.var="date")

d2H_sitosterol_B <- melt(subset(d2H_H2O_lipids_chlorMax, select= c(date,sitosterol_Avg.d2H_VSMOW)),id.var="date")
d2H.SD_sitosterol_B <- melt(subset(d2H_H2O_lipids_chlorMax, select= c(date,sitosterol_SD.d2H_VSMOW)),id.var="date")

d2H_stigmasterol_B <- melt(subset(d2H_H2O_lipids_chlorMax, select= c(date,stigmasterol_Avg.d2H_VSMOW)),id.var="date")
d2H.SD_stigmasterol_B <- melt(subset(d2H_H2O_lipids_chlorMax, select= c(date,stigmasterol_SD.d2H_VSMOW)),id.var="date")

```

## plotting d2H values of lake water, C16:0 and phytol 

```{r}

#Fig. 4

#surface water

pd2H_water_surface <- ggplot(d2H_H2O_A, aes(x = date, y = value)) + 
  ggtitle("1 m depth", subtitle= "1 m depth")+
  scale_y_continuous(position = "left", sec.axis = sec_axis~.)+
  annotate("text",y= 67.5, x= as.Date("2018-11-10"),label="A", size=15, fontface=2, color="black")+
  coord_cartesian(ylim=c(-200,0),x=as.Date(c("2019-01-30", "2020-02-18")), clip="off")+
  geom_line(aes(),color= "steelblue3", linewidth=1)+
  geom_point(aes(), fill= "steelblue3", shape=23, size=4,alpha=0.8)+
  ylab(expression(atop(delta^2*H['water'],("\211"*","~VSMOW)))) + xlab(NULL)+ 
  geom_errorbar(aes(ymin=value-d2H.SD_H2O_A$value, ymax=value+d2H.SD_H2O_A$value), color="black", width=9)+
  facet_grid(variable ~ .,scales='free_x', switch='y', labeller = as_labeller(c(H2O_Avg.d2H_VSMOW = 'd2H H2O')))+
  xlab(NULL)+ 
  theme(axis.line = element_line(colour = "black"), 
        plot.title= element_text(size=35, face= "bold"),
        plot.subtitle= element_text(size=15, color="white"),
        panel.background = element_blank(),
        axis.line.x =element_blank(),
        axis.ticks.x = element_blank(),
        axis.text.x = element_blank(),
        axis.line.y.right =element_blank(),
        axis.ticks.y.right = element_blank(),
        axis.text.y.left = element_text(size=30,color='steelblue3', face="bold"),
        axis.text.y.right = element_blank(),
        axis.title.y.left =  element_text(size=30,color='steelblue3', face="bold"),
        legend.position = "none",
        strip.background = element_blank(),
        strip.placement = "outside",
        strip.text = element_blank(),
        plot.margin = unit(c(1,0,0,0.25), "cm"))


pd2H_C16_surface <- ggplot(d2H_C16.0_A[!is.na(d2H_C16.0_A$value),], aes(x = date, y = value)) + 
  scale_y_continuous(position = "left", limits=c(-350,-150), sec.axis = sec_axis~.)+
  geom_line(aes(),color= "tomato", linewidth=1)+
  geom_point(aes(),fill= "tomato", shape=23, size=4,alpha=0.8)+
  geom_errorbar(aes(ymin=value-na.omit(d2H.SD_C16.0_A$value), ymax=value+na.omit(d2H.SD_C16.0_A$value)),
                color="black", width=9)+
  annotate(geom = "text", x = as.Date("2019-03-10"), y = -160, label = expression(R^2~"= 0.26"*"**"),
           color="tomato", size=12.5)+
  facet_grid(variable ~ ., scales='free_x',labeller = as_labeller(c(C16.0_Avg.d2H_VSMOW = 'd2H C16:0')))+
  xlab(NULL)+ ylab(NULL)+
  theme(axis.line = element_blank(), 
        panel.background = element_blank(),
        axis.line.x =element_blank(),
        axis.ticks.x = element_blank(),
        axis.text.x = element_blank(),
        axis.line.y.left =element_blank(),
        axis.ticks.y.left = element_blank(),
        axis.ticks.y.right = element_blank(),
        axis.text.y.left = element_blank(),
        axis.text.y.right = element_blank(),
        legend.position = "none",
        strip.background = element_blank(),
        strip.placement = "outside",
        strip.text = element_text(size = 1, color= "white", face='bold'),
        plot.margin = unit(c(0,0,0,0.25), "cm"))


pd2H_phytol_surface <- ggplot(d2H_phytol_A[!is.na(d2H_phytol_A$value),], aes(x = date, y = value)) + 
  scale_y_continuous(position = "left", limits=c(-500,-300), sec.axis = sec_axis~.)+
  geom_line(aes(),color= "seagreen3", linewidth=1)+
  geom_point(aes(), fill= "seagreen3", shape=23, size=4,alpha=0.8)+
  annotate(geom = "text", x = as.Date( "2019-03-14"), y = -315, label = expression(R^2~"= -0.05"),
           color="seagreen3", size=12.5)+
  geom_errorbar(aes(ymin=value-na.omit(d2H.SD_phytol_A$value), ymax=value+na.omit(d2H.SD_phytol_A$value)),
                color="black", width=9)+
  facet_grid(variable ~ ., scales='free_x', switch= "y", labeller = as_labeller(c(phytol_Avg.d2H_VSMOW= 'd2H phytol')))+
  ylab(expression(atop(delta^2*H['phytol'],("\211"*","~VSMOW)))) + xlab(NULL)+
  theme(axis.line = element_line(colour = "black"), 
        panel.background = element_blank(),
        axis.line.x =element_line(color='black'),
        axis.text.x = element_text(size=30, color= 'black', face="bold"),
        axis.text.y.left = element_text(size=30, color="seagreen3", face="bold"),
        axis.line.y.right =element_blank(),
        axis.ticks.y.right = element_blank(),
        axis.text.y.right = element_blank(),
        axis.title.y.left = element_text(size=30, color="seagreen3", face="bold"),
        legend.position = "none",
        strip.background = element_blank(),
        strip.placement = "outside",
        strip.text = element_blank(),
        plot.margin = unit(c(0,0,0.5,0.25), "cm"))


pd2H_surface1 <- plot_grid(pd2H_water_surface, pd2H_C16_surface, pd2H_phytol_surface, ncol=1,  
                           rel_heights = c(1.105, 0.805,0.9475), align = "v", axis="lr")


#chlorophyll maximum depth 

pd2H_water_chlorMax <- ggplot(d2H_H2O_B[!is.na(d2H_H2O_B$value),], aes(x = date, y = value)) + 
  ggtitle("chlorophyll maximum depth",subtitle= "chlorophyll maximum depth")+
  scale_y_continuous(position = "right", sec.axis = sec_axis~.)+
  geom_line(aes(),color= "steelblue3", linewidth=1)+
  geom_point(aes(fill= variable), shape=23, size=4,alpha=0.8)+
  annotate("text",y= 67.5, x= as.Date("2018-12-15"),label="B", size=15, fontface=2, color="black")+
  coord_cartesian(ylim=c(-200,0),x=as.Date(c("2019-01-30", "2020-02-18")), clip="off")+
  scale_fill_manual(labels=c("H2O_Avg.d2H_VSMOW"= expression(delta^2*H['water'])),
                    values=c(H2O_Avg.d2H_VSMOW="steelblue3"))+
  geom_errorbar(aes(ymin=value-na.omit(d2H.SD_H2O_B$value), ymax=value+na.omit(d2H.SD_H2O_B$value)), color="black", width=9)+
  facet_grid(variable ~ .,scales='free_x', switch="y", labeller = as_labeller(c(H2O_Avg.d2H_VSMOW = 'd2H H2O')))+
  xlab(NULL)+ ylab(NULL)+
  theme(axis.line = element_line(colour = "white"), 
        plot.title = element_text(size = 35, face= "bold"),
        plot.subtitle= element_text(size=15, color="white"),
        panel.background = element_blank(),
        axis.line.x =element_blank(),
        axis.ticks.x = element_blank(),
        axis.text.x = element_blank(),
        axis.line.y.right =element_line(color='white'),
        axis.ticks.y.right = element_blank(),
        axis.ticks.y.left = element_blank(),
        axis.text.y.right = element_blank(),
        axis.text.y.left = element_blank(),
        legend.position = "none",
        strip.background = element_blank(),
        strip.placement = "outside",
        strip.text = element_text(size = 1, color= 'white', face= "bold"),
        plot.margin = unit(c(1,0,0,0), "cm"))


pd2H_C16_chlorMax <- ggplot(d2H_C16.0_B[!is.na(d2H_C16.0_B$value),], aes(x = date, y = value)) + 
  scale_y_continuous(position = "right", limits=c(-350,-150), sec.axis = sec_axis~.)+
  geom_line(aes(),color= "tomato", linewidth=1)+
  geom_point(aes(fill= variable), shape=23, size=4,alpha=0.8)+
  scale_fill_manual(labels=c("C16.0_Avg.d2H_VSMOW"= expression(delta^2*H['C16:0'])),
                    values=c(C16.0_Avg.d2H_VSMOW="tomato"))+
  geom_errorbar(aes(ymin=value-na.omit(d2H.SD_C16.0_B$value), ymax=value+na.omit(d2H.SD_C16.0_B$value)),
                color="black", width=9)+
  facet_grid(variable ~ ., scales='free_x',labeller = as_labeller(c(C16.0_Avg.d2H_VSMOW = 'd2H C16:0')))+
  annotate(geom = "text", x = as.Date("2019-03-14"), y = -160, label = expression(R^2~"= -0.04"), color="tomato",
           size=12.5)+
  ylab(expression(atop(delta^2*H['C16:0'],("\211"*","~VSMOW)))) + xlab(NULL)+ 
  theme(axis.line = element_line(colour = "black"), 
        panel.background = element_blank(),
        axis.line.x =element_blank(),
        axis.ticks.x = element_blank(),
        axis.text.x = element_blank(),
        axis.line.y.left =element_line(color='white'),
        axis.ticks.y.left = element_blank(),
        axis.text.y.left = element_blank(),
        axis.text.y.right = element_text(size=30, color= 'tomato', face= 'bold'),
        axis.title.y.right =  element_text(size=30,color="tomato", face="bold"),
        legend.position = "none",
        strip.background = element_blank(),
        strip.placement = "outside",
        strip.text = element_blank())


pd2H_phytol_chlorMax <- ggplot(d2H_phytol_B[!is.na(d2H_phytol_B$value),], aes(x = date, y = value)) + 
  scale_y_continuous(position = "right", limits=c(-500,-300), sec.axis = sec_axis~.)+
  geom_line(aes(),color= "seagreen3", linewidth=1)+
  geom_point(aes(fill= variable), shape=23, size=4, alpha=0.8)+
  scale_fill_manual(labels=c("phytol_Avg.d2H_VSMOW"= expression(delta^2*H['phytol'])),
                    values=c(phytol_Avg.d2H_VSMOW="seagreen3"))+
  geom_errorbar(aes(ymin=value-na.omit(d2H.SD_phytol_B$value), ymax=value+na.omit(d2H.SD_phytol_B$value)),
                color="black", width=9)+
  annotate(geom = "text", x = as.Date( "2019-03-10"),
           y = -315, label = expression(R^2~"= 0.04"), color="seagreen3", size=12.5)+
  facet_grid(variable ~ ., scales='free_x', switch= "y", labeller = as_labeller(c(phytol_Avg.d2H_VSMOW = 'd2H
                                                                                                  phytol')))+
  xlab(NULL)+ ylab(NULL)+
  theme(axis.line = element_line(colour = "white"), 
        panel.background = element_blank(),
        axis.line.x =element_line(color='black'),
        axis.text.x = element_text(size=30, face="bold", color='black'),
        axis.text.y.left = element_blank(),
        axis.line.y.right =element_blank(),
        axis.ticks.y.right = element_blank(),
        axis.ticks.y.left = element_blank(),
        axis.text.y.right = element_blank(),
        legend.position = "none",
        strip.background = element_blank(),
        strip.placement = "outside",
        strip.text = element_blank(),
        plot.margin = unit(c(0,0,0.5,0), "cm"))


pd2H_chlorMax1 <- plot_grid(pd2H_water_chlorMax, pd2H_C16_chlorMax, pd2H_phytol_chlorMax, rel_heights = c(1.105, 0.805, 0.9475),
                            ncol=1, align = "v", axis="lr")



Fig4 <- plot_grid(pd2H_surface1, pd2H_chlorMax1, ncol=2, rel_widths = c(1,1), align="h") 


```


## Fig. 4


```{r, fig.width = 25, fig.height = 10, echo=FALSE}

plot(Fig4)

```

