---
title: "S02-Temperature & Dissolved Oxygen Profile"
author: "Antonia_Klatt"
date: "2024-07-31"
output: html_document
---

```{r}
knitr::opts_chunk$set(echo = TRUE)

#loading packages

library(readr)
library(here)
library(ggplot2)
library(cowplot)
library(reshape2)

#import oxygen and temperature data for different sampling dates

Temp_Ox_ROT190410 <- read.csv(here("01_Data","temp_oxygen_profile_watercolumn_ROT190410.csv"), header = TRUE , sep = ";" , stringsAsFactors = FALSE, na.strings = "#NV")

Temp_Ox_ROT190717 <- read.csv(here("01_Data","temp_oxygen_profile_watercolumn_ROT190717.csv"), header = TRUE , sep = ";" , stringsAsFactors = FALSE, na.strings = "#NV")

Temp_Ox_ROT190925 <- read.csv(here("01_Data","temp_oxygen_profile_watercolumn_ROT190925.csv"), header = TRUE , sep = ";" , stringsAsFactors = FALSE, na.strings = "#NV")

Temp_Ox_ROT191023 <- read.csv(here("01_Data","temp_oxygen_profile_watercolumn_ROT191023.csv"), header = TRUE , sep = ";" , stringsAsFactors = FALSE, na.strings = "#NV")

Temp_Ox_ROT191218 <- read.csv(here("01_Data","temp_oxygen_profile_watercolumn_ROT191218.csv"), header = TRUE , sep = ";" , stringsAsFactors = FALSE, na.strings = "#NV")


#reshape temperature and oxygen dataframes for each date

ROT190410_Temp <- melt(subset(Temp_Ox_ROT190410, select= c(temp_C, depth_m)),id.var="depth_m")
ROT190410_Ox <- melt(subset(Temp_Ox_ROT190410, select= c(DO_mgL, depth_m)),id.var="depth_m")

ROT190717_Temp <- melt(subset(Temp_Ox_ROT190717, select= c(temp_C, depth_m)),id.var="depth_m")
ROT190717_Ox <- melt(subset(Temp_Ox_ROT190717, select= c(DO_mgL, depth_m)),id.var="depth_m")

ROT190925_Temp <- melt(subset(Temp_Ox_ROT190925, select= c(temp_C, depth_m)),id.var="depth_m")
ROT190925_Ox <- melt(subset(Temp_Ox_ROT190925, select= c(DO_mgL, depth_m)),id.var="depth_m")

ROT191023_Temp <- melt(subset(Temp_Ox_ROT191023, select= c(temp_C, depth_m)),id.var="depth_m")
ROT191023_Ox <- melt(subset(Temp_Ox_ROT191023, select= c(DO_mgL, depth_m)),id.var="depth_m")

ROT191218_Temp <- melt(subset(Temp_Ox_ROT191218, select= c(temp_C, depth_m)),id.var="depth_m")
ROT191218_Ox <- melt(subset(Temp_Ox_ROT191218, select= c(DO_mgL, depth_m)),id.var="depth_m")

```

## plotting temperature and oxygen profiles for different sampling dates

```{r}

#Fig. 2

#create depth vector for plotting 

ROT_depth <- c(seq(from=0, to= 16, by=1)) 


#select n rows for a better visualization 

#temperature

ROT190410_Temp1 = ROT190410_Temp[seq(10, nrow(ROT190410_Temp), 10), ]
ROT190717_Temp1 = ROT190717_Temp[seq(10, nrow(ROT190717_Temp), 10), ] 
ROT190925_Temp1 = ROT190925_Temp[seq(10, nrow(ROT190925_Temp), 10), ] 
ROT191023_Temp1 = ROT191023_Temp[seq(20, nrow(ROT191023_Temp), 10), ]
ROT191218_Temp1 = ROT191218_Temp[seq(10, nrow(ROT191218_Temp), 10), ]


#DO

ROT190410_Ox1 = ROT190410_Ox[seq(20, nrow(ROT190410_Ox), 10), ]
ROT190717_Ox1 = ROT190717_Ox[seq(20, nrow(ROT190717_Ox),10), ] 
ROT190925_Ox1 = ROT190925_Ox[seq(20, nrow(ROT190925_Ox), 10), ] 
ROT191023_Ox1 = ROT191023_Ox[seq(20, nrow(ROT191023_Ox), 10), ]
ROT191218_Ox1 = ROT191218_Ox[seq(20, nrow(ROT191218_Ox), 10), ]


pSpring <- ggplot()+
  geom_point(data=ROT190410_Ox1, aes(x = value+5, y=depth_m), color="royalblue2", shape=20, size=2)+
  geom_point(data=ROT190410_Temp1, aes(x = value, y=depth_m), color="red3", shape=20, size=2)+
  scale_x_continuous("temperature (°C)", breaks=c(0,5,10,15,20,25), position = "bottom", sec.axis = dup_axis((~ .-5 ), name= "dissolved oxygen [mg/L]"))+
  ylab("depth (m)")+ xlab("temperature")+
  coord_cartesian(clip="off", ylim= rev(range(ROT_depth)), xlim=c(5,27.5))+
  geom_hline(yintercept = 1, color="black", linetype= "dashed")+
  geom_hline(yintercept = 4, color="black", linetype= "dashed")+
  #annotate("text",x=22.5 ,y=5,label="establishment stratification", fontface=2, size=8,color="black")+
  annotate("text",x=20 ,y=14.5,label="2019-04-10", fontface=2, size=8,color="black")+
  #annotate("text",x=25 ,y=4.5,label="thermocline", fontface=2, size=8,color="lightsalmon")+
  #annotate("text",x=25 ,y=5.5,label="oxycline", fontface=2, size=8,color="lightsalmon")+
  theme(axis.line = element_line(colour = "black"),
        legend.position="right",
        panel.background = element_blank(),
        panel.border = element_blank(),
        axis.text.x = element_text(face='bold',color="red3", size=27.5),
        axis.text.x.top = element_text(face='bold',color="royalblue2", size=27.5),
        axis.text.y = element_text(face='bold', color='black', size=27.5),
        #axis.title.x = element_text(color="red3", size=27.5),
       # axis.title.x.top = element_text( color="royalblue1", size=27.5),
       axis.title.x = element_blank(),
       axis.title.x.top = element_blank(),
        axis.title.y = element_text( color='black', size=27.5),
        legend.title = element_text(size=27.5, face= "bold"),
        legend.background=element_blank(),
        legend.key=element_rect(fill="white"),
        legend.text=element_text(size=27.5),
        legend.key.height= unit(0.7, 'cm'),
        legend.key.width= unit(0.7, 'cm'),
        legend.spacing.y = unit(0.25, "cm"),
        plot.margin = unit(c(1.35,0.25,1.35,0.25), "cm"))


pSummer <- ggplot()+
  annotate("rect", xmin = -Inf ,xmax = Inf ,ymin = 4.25, ymax = 10.25, alpha=0.16, fill="lightsalmon")+
  geom_point(data=ROT190717_Ox1, aes(x = value+5, y=depth_m), color="royalblue2", shape=20, size=2)+
  geom_point(data=ROT190717_Temp1, aes(x = value, y=depth_m), color="red3", shape=20, size=2)+
  scale_x_continuous("temperature (°C)", breaks=c(0,5,10,15,20,25), position = "bottom", sec.axis = dup_axis((~ . -5), name= "dissolved oxygen [mg/L]"))+
  ylab("depth (m)")+ xlab("temperature")+
  coord_cartesian(clip="off", ylim= rev(range(ROT_depth)), xlim=c(5,27.5))+
  geom_hline(yintercept = 1, color="black", linetype= "dashed")+
  geom_hline(yintercept = 12, color="black", linetype= "dashed")+
  #annotate("text",x=22.5 ,y=5,label="stratification", fontface=2, size=8,color="black")+
  annotate("text",x=20 ,y=14.5,label="2019-07-17", fontface=2, size=8,color="black")+
  theme(axis.line = element_line(colour = "black"),
        legend.position="right",
        panel.background = element_blank(),
        panel.border = element_blank(),
        axis.text.x = element_text(face='bold',color="red3", size=27.5),
        axis.text.x.top = element_text(face='bold',color="royalblue2", size=27.5),
        axis.text.y = element_blank(),
        axis.line.y = element_blank(),
        axis.ticks.y = element_blank(),
        axis.title.y= element_blank(),
        #axis.title.x = element_text(color="red3", size=27.5),
        # axis.title.x.top = element_text( color="royalblue1", size=27.5),
        axis.title.x = element_blank(),
        axis.title.x.top = element_blank(),
        legend.title = element_text(size=27.5, face= "bold"),
        legend.background=element_blank(),
        legend.key=element_rect(fill="white"),
        legend.text=element_text(size=27.5),
        legend.key.height= unit(0.7, 'cm'),
        legend.key.width= unit(0.7, 'cm'),
        legend.spacing.y = unit(0.25, "cm"),
        plot.margin = unit(c(1.35,0.25,1.35,0.25), "cm"))



pAutumn1 <- ggplot()+
  annotate("rect", xmin = -Inf ,xmax = Inf ,ymin = 4.25, ymax = 10.25, alpha=0.16, fill="lightsalmon")+
  geom_point(data=ROT190925_Ox1, aes(x = value+5, y=depth_m), color="royalblue2", shape=20, size=2)+
  geom_point(data=ROT190925_Temp1, aes(x = value, y=depth_m), color="red3", shape=20, size=2)+
  scale_x_continuous("temperature (°C)", breaks=c(0,5,10,15,20,25), position = "bottom", sec.axis = dup_axis((~ . -5),name= "dissolved oxygen [mg/L]"))+
  ylab("depth (m)")+ xlab("temperature")+
  coord_cartesian(clip="off", ylim= rev(range(ROT_depth)), xlim=c(5,27.5))+
  geom_hline(yintercept = 1, color="black", linetype= "dashed")+
  geom_hline(yintercept = 10, color="black", linetype= "dashed")+
  #annotate("text",x=22.5 ,y=5,label="stratification", fontface=2, size=8,color="black")+
  annotate("text",x=20 ,y=14.5,label="2019-09-25", fontface=2, size=8,color="black")+
  annotate("text",x=15 ,y=-5,label="dissolved oxygen [mg/L]", size=9.25,color="royalblue2")+
  annotate("text",x=16 ,y=20.5,label="temperature (°C)", size=9.25,color="red3")+
  theme(axis.line = element_line(colour = "black"),
        legend.position="right",
        panel.background = element_blank(),
        panel.border = element_blank(),
        axis.text.x = element_text(face='bold',color="red3", size=27.5),
        axis.text.x.top = element_text(face='bold',color="royalblue2", size=27.5),
        #axis.title.x = element_text(color="red3", size=27.5),
        #axis.title.x.top = element_text( color="royalblue1", size=27.5),
        axis.title.x = element_blank(),
        axis.title.x.top = element_blank(),
        axis.text.y = element_blank(),
        axis.line.y = element_blank(),
        axis.ticks.y = element_blank(),
        axis.title.y= element_blank(),
        legend.title = element_text(size=27.5, face= "bold"),
        legend.background=element_blank(),
        legend.key=element_rect(fill="white"),
        legend.text=element_text(size=27.5),
        legend.key.height= unit(0.7, 'cm'),
        legend.key.width= unit(0.7, 'cm'),
        legend.spacing.y = unit(0.25, "cm"),
        plot.margin = unit(c(1.35,0.5,1.35,0.5), "cm"))



pAutumn2 <- ggplot()+
  geom_point(data=ROT191023_Ox1, aes(x = value+5, y=depth_m), color="royalblue2", shape=20, size=2)+
  geom_point(data=ROT191023_Temp1, aes(x = value, y=depth_m), color="red3", shape=20, size=2)+
  scale_x_continuous("temperature (°C)", breaks=c(0,5,10,15,20,25), position = "bottom", sec.axis = dup_axis((~ . -5), name= "dissolved oxygen [mg/L]"))+
  ylab("depth (m)")+ xlab("temperature")+
  coord_cartesian(clip="off", ylim= rev(range(ROT_depth)), xlim=c(5,27.5))+
  geom_hline(yintercept = 1, color="black", linetype= "dashed")+
  geom_hline(yintercept = 10, color="black", linetype= "dashed")+
  #annotate("text",x=22.5 ,y=5,label="onset turnover", fontface=2, size=8,color="black")+
  annotate("text",x=20 ,y=14.5,label="2019-10-23", fontface=2, size=8,color="black")+
  theme(axis.line = element_line(colour = "black"),
        legend.position="right",
        panel.background = element_blank(),
        panel.border = element_blank(),
        axis.text.x = element_text(face='bold',color="red3", size=27.5),
        axis.text.x.top = element_text(face='bold',color="royalblue2", size=27.5),
        axis.text.y = element_blank(),
        axis.line.y = element_blank(),
        axis.ticks.y = element_blank(),
        axis.title.y= element_blank(),
        #axis.title.x = element_text(color="red3", size=27.5),
        # axis.title.x.top = element_text( color="royalblue1", size=27.5),
        axis.title.x = element_blank(),
        axis.title.x.top = element_blank(),
        legend.title = element_text(size=27.5, face= "bold"),
        legend.background=element_blank(),
        legend.key=element_rect(fill="white"),
        legend.text=element_text(size=27.5),
        legend.key.height= unit(0.7, 'cm'),
        legend.key.width= unit(0.7, 'cm'),
        legend.spacing.y = unit(0.25, "cm"),
        plot.margin = unit(c(1.35,0.5,1.35,0.5), "cm"))



pWinter <- ggplot()+
  geom_point(data=ROT191218_Ox1, aes(x = value+5, y=depth_m), color="royalblue2", shape=20, size=2)+
  geom_point(data=ROT191218_Temp1, aes(x = value, y=depth_m), color="red3", shape=20, size=2)+
  scale_x_continuous("temperature (°C)", breaks=c(0,5,10,15,20,25), position = "bottom", sec.axis = dup_axis((~ . -5 ),name= "dissolved oxygen [mg/L]"))+
  scale_y_continuous("depth (m)", breaks=c(0,5,10,15), position = "left", sec.axis = sec_axis((~ . ),name= "depth (m)"))+
  ylab("depth (m)")+ xlab("temperature")+
  coord_cartesian(clip="off", ylim= rev(range(ROT_depth)), xlim=c(5,27.5))+
  geom_hline(yintercept = 1, color="black", linetype= "dashed")+
  geom_hline(yintercept = 4, color="black", linetype= "dashed")+
  #annotate("text",x=22.5 ,y=5,label="vertical mixing", fontface=2, size=8,color="black")+
  annotate("text",x=20 ,y=14.5,label="2019-12-18", fontface=2, size=8,color="black")+
  theme(axis.line = element_line(colour = "black"),
        legend.position="right",
        panel.background = element_blank(),
        panel.border = element_blank(),
        axis.text.x = element_text(face='bold',color="red3", size=27.5),
        axis.text.x.top = element_text(face='bold',color="royalblue2", size=27.5),
        axis.text.y.right = element_text(face='bold', color='black', size=27.5),
        axis.text.y.left = element_blank(),
        axis.line.y.left = element_blank(),
        axis.ticks.y.left = element_blank(),
        #axis.title.x = element_text(color="red3", size=27.5),
        # axis.title.x.top = element_text( color="royalblue1", size=27.5),
        axis.title.x = element_blank(),
        axis.title.x.top = element_blank(),
        axis.title.y.right = element_blank(),
        axis.title.y.left = element_blank(),
        legend.title = element_text(size=27.5, face= "bold"),
        legend.background=element_blank(),
        legend.key=element_rect(fill="white"),
        legend.text=element_text(size=27.5),
        legend.key.height= unit(0.7, 'cm'),
        legend.key.width= unit(0.7, 'cm'),
        legend.spacing.y = unit(0.25, "cm"),
        plot.margin = unit(c(1.35,0.5,1.35,0.5), "cm"))

FigS2 <- plot_grid(pSpring, pSummer, pAutumn1, pAutumn2, pWinter, ncol=5, align= "h", rel_widths = c(1.2,0.95,1.1,1,1.15))

```

## Fig. S2

```{r, fig.width = 20, fig.height = 5, echo=FALSE}

plot(FigS2)

```
