---
title: "S06_lipid_concentrations"
author: "Antonia_Klatt"
date: "2024-08-07"
output: html_document
---

```{r}
knitr::opts_chunk$set(echo = TRUE)

library(readr)
library(here)
library(ggplot2)
library(reshape2)
library(cowplot)

Sys.setlocale("LC_ALL", "English")

#import lipid concentration data

lipid_conc <- read.csv(here("01_Data","Lipid_conc_watercolumn_ROT19.csv"), header = TRUE , sep = ";" , stringsAsFactors = FALSE, na.strings = "#NV")


#note: data frame includes two different depths: surface water (A) and chlorophyll maximum depth (B)

#separate sampling depths

lipid_conc_surface <- lipid_conc[1:24,]

lipid_conc_chlorMax <- lipid_conc[25:47,]


#setting dates for plotting

sampling_dates_A <- c("2019-01-30","2019-02-13", "2019-03-13", "2019-03-27",
                      "2019-04-10", "2019-04-24", "2019-05-08",
                      "2019-05-22", "2019-06-04", "2019-06-19",
                      "2019-07-17", "2019-07-30", "2019-08-14",
                      "2019-09-11", "2019-09-25", "2019-10-09",
                      "2019-10-23", "2019-11-06","2019-11-20",
                      "2019-12-04", "2019-12-18", "2020-01-07", "2020-01-21",
                      "2020-02-06")

sampling_dates_B <- c("2019-01-30","2019-02-13", "2019-03-13", 
                      "2019-04-10", "2019-04-24", "2019-05-08",
                      "2019-05-22", "2019-06-04", "2019-06-19",
                      "2019-07-17", "2019-07-30", "2019-08-14",
                      "2019-09-11", "2019-09-25", "2019-10-09",
                      "2019-10-23", "2019-11-06","2019-11-20",
                      "2019-12-04", "2019-12-18", "2020-01-07", "2020-01-21",
                      "2020-02-06")

rownames(lipid_conc_surface) <-sampling_dates_A
rownames(lipid_conc_chlorMax) <-sampling_dates_B

lipid_conc_surface$date <- as.Date(rownames(lipid_conc_surface), "%Y-%m-%d")
lipid_conc_chlorMax$date <- as.Date(rownames(lipid_conc_chlorMax), "%Y-%m-%d")


```
## alcohol concentrations watercolumn

```{r}

#surface water

brassicasterol_A <- melt(subset(lipid_conc_surface, select= c(date,brassicasterol_ugL)),id.var="date")

cholesterol_A <- melt(subset(lipid_conc_surface, select= c(date,cholesterol_ugL)),id.var="date")

diplopterol_A <- melt(subset(lipid_conc_surface, select= c(date,diplopterol_ugL)),id.var="date")

ergosterol_A <- melt(subset(lipid_conc_surface, select= c(date,ergosterol_ugL)),id.var="date")

sitosterol_A <- melt(subset(lipid_conc_surface, select= c(date,sitosterol_ugL)),id.var="date")

stigmasterol_A <- melt(subset(lipid_conc_surface, select= c(date,stigmasterol_ugL)),id.var="date")

phytol_A <- melt(subset(lipid_conc_surface, select= c(date,phytol_ugL)),id.var="date")



#chlorophyll maximum depth

brassicasterol_B <- melt(subset(lipid_conc_chlorMax, select= c(date,brassicasterol_ugL)),id.var="date")

cholesterol_B <- melt(subset(lipid_conc_chlorMax, select= c(date,cholesterol_ugL)),id.var="date")

diplopterol_B <- melt(subset(lipid_conc_chlorMax, select= c(date,diplopterol_ugL)),id.var="date")

ergosterol_B <- melt(subset(lipid_conc_chlorMax, select= c(date,ergosterol_ugL)),id.var="date")

sitosterol_B <- melt(subset(lipid_conc_chlorMax, select= c(date,sitosterol_ugL)),id.var="date")

stigmasterol_B <- melt(subset(lipid_conc_chlorMax, select= c(date,stigmasterol_ugL)),id.var="date")

phytol_B <- melt(subset(lipid_conc_chlorMax, select= c(date,phytol_ugL)),id.var="date")

```
## plotting alcohol concentrations

```{r}

#surface

pBrass_surface <- ggplot() + 
  ggtitle("1 m depth", subtitle= "1 m depth")+
  geom_point(data=brassicasterol_A[!is.na(brassicasterol_A$value),], aes(x=date,y=value), fill= "black", shape= 23, size=3,alpha=0.8)+
  geom_line(data=brassicasterol_A[!is.na(brassicasterol_A$value),], aes(x=date,y=value),color= "black",  linewidth= 1)+ 
  annotate("text",y= 2.2, x= as.Date("2018-11-30"),label="A", size=15, fontface=2, color="black")+
  coord_cartesian(ylim=c(0,1.5),x=as.Date(c("2019-01-30", "2020-02-06")), clip="off")+
  scale_y_continuous(breaks=c(0.0,0.5,1,1.5))+
  ylab(expression(atop("brassicasterol","[µg/L]"))) + xlab(NULL)+
  theme(axis.line = element_line(colour = "black"),
        plot.title= element_text(size=35, face= "bold"),
        plot.subtitle= element_text(size=15, color="white"),
        panel.background = element_blank(),
        axis.line.x =element_blank(),
        axis.ticks.x = element_blank(),
        axis.text.x = element_blank(),
        axis.text.y = element_text(size=30,color='black', face="bold"),
        axis.title.y = element_text(size=30,color='black', face="bold"),
        legend.position = "none",
        strip.background = element_blank(),
        strip.placement = "outside",
        strip.text = element_text(size = 30, color= 'black', face="bold"),
        plot.margin = unit(c(1,0,1.25,0.5), "cm"))



pChol_surface <- ggplot() + 
  geom_point(data=cholesterol_A[!is.na(cholesterol_A$value),], aes(x=date,y=value), fill= "black", shape= 23, size=3,alpha=0.8)+
  geom_line(data=cholesterol_A[!is.na(cholesterol_A$value),], aes(x=date,y=value),color= "black",  linewidth= 1)+ 
  coord_cartesian(ylim=c(0,1.5),x=as.Date(c("2019-01-30", "2020-02-06")), clip="off")+
  ylab(expression(atop("cholesterol","[µg/L]"))) + xlab(NULL)+
  scale_y_continuous(breaks=c(0.0,0.5,1,1.5))+
  theme(axis.line = element_line(colour = "black"),
        panel.background = element_blank(),
        axis.line.x =element_blank(),
        axis.ticks.x = element_blank(),
        axis.text.x = element_blank(),
        axis.text.y = element_text(size=30,color='black', face="bold"),
        axis.title.y = element_text(size=30,color='black', face="bold"),
        legend.position = "none",
        strip.background = element_blank(),
        strip.placement = "outside",
        strip.text = element_text(size = 30, color= 'black', face="bold"),
        plot.margin = unit(c(0,0,1,0.5), "cm"))

pDip_surface <- ggplot() + 
  geom_point(data=cholesterol_A[!is.na(diplopterol_A$value),], aes(x=date,y=value), fill= "black", shape= 23, size=3,alpha=0.8)+
  geom_line(data=cholesterol_A[!is.na(diplopterol_A$value),], aes(x=date,y=value),color= "black",  linewidth= 1)+ 
  coord_cartesian(ylim=c(0,1.5),x=as.Date(c("2019-01-30", "2020-02-06")), clip="off")+
  ylab(expression(atop("diplopterol","[µg/L]"))) + xlab(NULL)+
  scale_y_continuous(breaks=c(0.0,0.5,1,1.5))+
  theme(axis.line = element_line(colour = "black"),
        panel.background = element_blank(),
        axis.line.x =element_blank(),
        axis.ticks.x = element_blank(),
        axis.text.x = element_blank(),
        axis.text.y = element_text(size=30,color='black', face="bold"),
        axis.title.y = element_text(size=30,color='black', face="bold"),
        legend.position = "none",
        strip.background = element_blank(),
        strip.placement = "outside",
        strip.text = element_text(size = 30, color= 'black', face="bold"),
        plot.margin = unit(c(0,0,1,0.5), "cm"))

pErgo_surface <- ggplot() + 
  geom_point(data=ergosterol_A[!is.na(ergosterol_A$value),], aes(x=date,y=value), fill= "black", shape= 23, size=3,alpha=0.8)+
  geom_line(data=ergosterol_A[!is.na(ergosterol_A$value),], aes(x=date,y=value),color= "black",  linewidth= 1)+ 
  coord_cartesian(ylim=c(0,1.5),x=as.Date(c("2019-01-30", "2020-02-06")), clip="off")+
  scale_y_continuous(breaks=c(0.0,0.5,1,1.5))+
  ylab(expression(atop("ergosterol","[µg/L]"))) + xlab(NULL)+
  theme(axis.line = element_line(colour = "black"),
        panel.background = element_blank(),
        axis.line.x =element_blank(),
        axis.ticks.x = element_blank(),
        axis.text.x = element_blank(),
        axis.text.y = element_text(size=30,color='black', face="bold"),
        axis.title.y = element_text(size=30,color='black', face="bold"),
        legend.position = "none",
        strip.background = element_blank(),
        strip.placement = "outside",
        strip.text = element_text(size = 30, color= 'black', face="bold"),
        plot.margin = unit(c(0,0,1,0.5), "cm"))



pSito_surface <- ggplot() + 
  geom_point(data=sitosterol_A[!is.na(sitosterol_A$value),], aes(x=date,y=value), fill= "black", shape= 23, size=3,alpha=0.8)+
  geom_line(data=sitosterol_A[!is.na(sitosterol_A$value),], aes(x=date,y=value),color= "black",  linewidth= 1)+ 
  coord_cartesian(ylim=c(0,5),x=as.Date(c("2019-01-30", "2020-02-06")), clip="off")+
  scale_y_continuous(breaks=c(0.0,2.5,5))+
  ylab(expression(atop("sitosterol","[µg/L]"))) + xlab(NULL)+
  theme(axis.line = element_line(colour = "black"),
        panel.background = element_blank(),
        axis.line.x =element_blank(),
        axis.ticks.x = element_blank(),
        axis.text.x = element_blank(),
        axis.text.y = element_text(size=30,color='black', face="bold"),
        axis.title.y = element_text(size=30,color='black', face="bold"),
        legend.position = "none",
        strip.background = element_blank(),
        strip.placement = "outside",
        strip.text = element_text(size = 30, color= 'black', face="bold"),
        plot.margin = unit(c(0,0,1,0.5), "cm"))


pStigma_surface <- ggplot() + 
  geom_point(data=stigmasterol_A[!is.na(stigmasterol_A$value),], aes(x=date,y=value), fill= "black", shape= 23, size=3,alpha=0.8)+
  geom_line(data=stigmasterol_A[!is.na(stigmasterol_A$value),], aes(x=date,y=value),color= "black",  linewidth= 1)+ 
  coord_cartesian(ylim=c(0,1.5),x=as.Date(c("2019-01-30", "2020-02-06")), clip="off")+
  scale_y_continuous(breaks=c(0.0,0.5,1,1.5))+
  ylab(expression(atop("stigmasterol","[µg/L]"))) + xlab(NULL)+
  theme(axis.line = element_line(colour = "black"),
        panel.background = element_blank(),
        axis.line.x =element_blank(),
        axis.ticks.x = element_blank(),
        axis.text.x = element_blank(),
        axis.text.y = element_text(size=30,color='black', face="bold"),
        axis.title.y = element_text(size=30,color='black', face="bold"),
        legend.position = "none",
        strip.background = element_blank(),
        strip.placement = "outside",
        strip.text = element_text(size = 30, color= 'black', face="bold"),
        plot.margin = unit(c(0,0,1,0.5), "cm"))


pPhytol_surface <- ggplot() + 
  geom_point(data=phytol_A[!is.na(phytol_A$value),], aes(x=date,y=value), fill= "black", shape= 23, size=3,alpha=0.8)+
  geom_line(data=phytol_A[!is.na(phytol_A$value),], aes(x=date,y=value),color= "black",  linewidth= 1)+ 
  coord_cartesian(ylim=c(0,15),x=as.Date(c("2019-01-30", "2020-02-06")), clip="off")+
  scale_y_continuous(breaks=c(0.0,5.0,10.0,15.0))+
  ylab(expression(atop("phytol","[µg/L]"))) + xlab(NULL)+
  theme(axis.line = element_line(colour = "black"),
        panel.background = element_blank(),
        axis.line.x =element_line(color="black"),
        axis.text.x = element_text(size=30,color='black', face="bold"),
        axis.line.y.left =element_line(color='black'),
        axis.text.y.left = element_text(size=30, color= 'black', face= 'bold'),
        axis.title.y.left = element_text(size=30, color= 'black', face= 'bold'),
        strip.background = element_blank(),
        strip.placement = "outside",
        strip.text = element_text(size = 30, color= 'black', face="bold"),
        plot.margin = unit(c(0,0,0.5,0.5), "cm"))



plot_alcohols_conc_surface <- plot_grid(pBrass_surface,pChol_surface, pDip_surface,pErgo_surface, pSito_surface, pStigma_surface,
                                        pPhytol_surface, ncol=1, align="v", 
                                        rel_heights = c(1.6,1,1,1,1,1,1.125), axis='lr')


#chlorophyll maximum depth

pBrass_chlorMax <- ggplot() + 
  ggtitle("chlorophyll maximum depth depth", subtitle= "1 m depth")+
  geom_point(data=brassicasterol_B[!is.na(brassicasterol_B$value),], aes(x=date,y=value, fill= variable), shape= 23, size=3,alpha=0.8)+
  geom_line(data=brassicasterol_B[!is.na(brassicasterol_B$value),], aes(x=date,y=value),color= "black",  linewidth= 1)+ 
  scale_fill_manual(labels=c("brassicasterol_ugL"= "brassicasterol [µg/L]"),
                    values=c(brassicasterol_ugL="black"))+
  annotate("text",y= 2.2, x= as.Date("2018-11-25"),label="B", size=15, fontface=2, color="black")+
  coord_cartesian(ylim=c(0,1.5),x=as.Date(c("2019-01-30", "2020-02-06")), clip="off")+
  scale_y_continuous(breaks=c(0.0,0.5,1,1.5))+
  ylab(expression(atop("brassicasterol","[µg/L]"))) + xlab(NULL)+
  theme(axis.line = element_line(colour = "black"),
        legend.position = "none",
        plot.title= element_text(size=35, face= "bold"),
        plot.subtitle= element_text(size=15, color="white"),
        panel.background = element_blank(),
        axis.line.x =element_blank(),
        axis.ticks.x = element_blank(),
        axis.text.x = element_blank(),
        axis.text.y = element_text(size=30,color='black', face="bold"),
        axis.title.y = element_blank(),
        strip.background = element_blank(),
        strip.placement = "outside",
        strip.text = element_text(size = 30, color= 'black', face="bold"),
        plot.margin = unit(c(1,0.5,1.25,0), "cm"))


pChol_chlorMax <- ggplot() + 
  geom_point(data=cholesterol_B[!is.na(cholesterol_B$value),], aes(x=date,y=value, fill=variable), shape= 23, size=3,alpha=0.8)+
  geom_line(data=cholesterol_B[!is.na(cholesterol_B$value),], aes(x=date,y=value),color= "black",  linewidth= 1)+ 
  scale_fill_manual(labels=c("cholesterol_ugL"= "cholesterol [µg/L]"),
                    values=c(cholesterol_ugL="black"))+
  coord_cartesian(ylim=c(0,1.5),x=as.Date(c("2019-01-30", "2020-02-06")), clip="off")+
  ylab(expression(atop("cholesterol","[µg/L]"))) + xlab(NULL)+
  scale_y_continuous(breaks=c(0.0,0.5,1,1.5))+
  theme(axis.line = element_line(colour = "black"),
        legend.position = "none",
        panel.background = element_blank(),
        axis.line.x =element_blank(),
        axis.ticks.x = element_blank(),
        axis.text.x = element_blank(),
        axis.text.y = element_text(size=30,color='black', face="bold"),
        axis.title.y = element_blank(),
        strip.background = element_blank(),
        strip.placement = "outside",
        strip.text = element_text(size = 30, color= 'black', face="bold"),
        plot.margin = unit(c(0,0.5,1,0), "cm"))

pDip_chlorMax <- ggplot() + 
  geom_point(data=cholesterol_B[!is.na(diplopterol_B$value),], aes(x=date,y=value, fill=variable), shape= 23, size=3,alpha=0.8)+
  geom_line(data=cholesterol_B[!is.na(diplopterol_B$value),], aes(x=date,y=value),color= "black",  linewidth= 1)+ 
  scale_fill_manual(labels=c("diplopterol_ugL"= "cholesterol [µg/L]"),
                    values=c(diplopterol_ugL="black"))+
  coord_cartesian(ylim=c(0,1.5),x=as.Date(c("2019-01-30", "2020-02-06")), clip="off")+
  ylab(expression(atop("diplopterol","[µg/L]"))) + xlab(NULL)+
  scale_y_continuous(breaks=c(0.0,0.5,1,1.5))+
  theme(axis.line = element_line(colour = "black"),
        legend.position = "none",
        panel.background = element_blank(),
        axis.line.x =element_blank(),
        axis.ticks.x = element_blank(),
        axis.text.x = element_blank(),
        axis.text.y = element_text(size=30,color='black', face="bold"),
        axis.title.y = element_blank(),
        strip.background = element_blank(),
        strip.placement = "outside",
        strip.text = element_text(size = 30, color= 'black', face="bold"),
        plot.margin = unit(c(0,0.5,1,0), "cm"))


pErgo_chlorMax <- ggplot() + 
  geom_point(data=ergosterol_B[!is.na(ergosterol_B$value),], aes(x=date,y=value, fill= variable), shape= 23, size=3,alpha=0.8)+
  geom_line(data=ergosterol_B[!is.na(ergosterol_B$value),], aes(x=date,y=value),color= "black",  linewidth= 1)+ 
  scale_fill_manual(labels=c("ergosterol_ugL"= "ergosterol [µg/L]"),
                    values=c(ergosterol_ugL="black"))+
  coord_cartesian(ylim=c(0,1.5),x=as.Date(c("2019-01-30", "2020-02-06")), clip="off")+
  scale_y_continuous(breaks=c(0.0,0.5,1,1.5))+
  ylab(expression(atop("ergosterol","[µg/L]"))) + xlab(NULL)+
  theme(axis.line = element_line(colour = "black"),
        legend.position = "none",
        panel.background = element_blank(),
        axis.line.x =element_blank(),
        axis.ticks.x = element_blank(),
        axis.text.x = element_blank(),
        axis.text.y = element_text(size=30,color='black', face="bold"),
        axis.title.y = element_blank(),
        strip.background = element_blank(),
        strip.placement = "outside",
        strip.text = element_text(size = 30, color= 'black', face="bold"),
        plot.margin = unit(c(0,0.5,1,0), "cm"))



pSito_chlorMax <- ggplot() + 
  geom_point(data=sitosterol_B[!is.na(sitosterol_B$value),], aes(x=date,y=value, fill= variable), shape= 23, size=3,alpha=0.8)+
  geom_line(data=sitosterol_B[!is.na(sitosterol_B$value),], aes(x=date,y=value),color= "black",  linewidth= 1)+ 
  scale_fill_manual(labels=c("sitosterol_ugL"= "sitosterol [µg/L]"),
                    values=c(sitosterol_ug.L="black"))+
  coord_cartesian(ylim=c(0,5),x=as.Date(c("2019-01-30", "2020-02-06")), clip="off")+
  scale_y_continuous(breaks=c(0.0,2.5,5))+
  ylab(expression(atop("sitosterol","[µg/L]"))) + xlab(NULL)+
  theme(axis.line = element_line(colour = "black"),
        legend.position = "none",
        panel.background = element_blank(),
        axis.line.x =element_blank(),
        axis.ticks.x = element_blank(),
        axis.text.x = element_blank(),
        axis.text.y = element_text(size=30,color='black', face="bold"),
        axis.title.y = element_blank(),
        strip.background = element_blank(),
        strip.placement = "outside",
        strip.text = element_text(size = 30, color= 'black', face="bold"),
        plot.margin = unit(c(0,0.5,1,0), "cm"))


pStigma_chlorMax <- ggplot() + 
  geom_point(data=stigmasterol_B[!is.na(stigmasterol_B$value),], aes(x=date,y=value, fill= variable), shape= 23, size=3,alpha=0.8)+
  geom_line(data=stigmasterol_B[!is.na(stigmasterol_B$value),], aes(x=date,y=value),color= "black",  linewidth= 1)+ 
  scale_fill_manual(labels=c("stigmasterol_ugL"= "stigmasterol [µg/L]"),
                    values=c(stigmasterol_ugL="black"))+
  coord_cartesian(ylim=c(0,1.5),x=as.Date(c("2019-01-30", "2020-02-06")), clip="off")+
  scale_y_continuous(breaks=c(0.0,0.5,1.0,1.5))+
  ylab(expression(atop("stigmasterol","[µg/L]"))) + xlab(NULL)+
  theme(axis.line = element_line(colour = "black"),
        legend.position = "none",
        panel.background = element_blank(),
        axis.line.x =element_blank(),
        axis.ticks.x = element_blank(),
        axis.text.x = element_blank(),
        axis.text.y = element_text(size=30,color='black', face="bold"),
        axis.title.y = element_blank(),
        strip.background = element_blank(),
        strip.placement = "outside",
        strip.text = element_text(size = 30, color= 'black', face="bold"),
        plot.margin = unit(c(0,0.5,1,0), "cm"))


pPhytol_chlorMax <- ggplot() + 
  geom_point(data=phytol_B[!is.na(phytol_B$value),], aes(x=date,y=value, fill= variable), shape= 23, size=3,alpha=0.8)+
  geom_line(data=phytol_B[!is.na(phytol_B$value),], aes(x=date,y=value),color= "black",  linewidth= 1)+ 
  scale_fill_manual(labels=c("phytol_ugL"= "phytol [µg/L]"),
                    values=c(phytol_ugL="black"))+
  coord_cartesian(ylim=c(0,15),x=as.Date(c("2019-01-30", "2020-02-06")), clip="off")+
  scale_y_continuous(breaks=c(0.0,5.0,10.0,15.0))+
  ylab(expression(atop("phytol","[µg/L]"))) + xlab(NULL)+
  theme(axis.line = element_line(colour = "black"),
        legend.position = "none",
        panel.background = element_blank(),
        axis.line.x =element_line(color="black"),
        axis.text.x = element_text(size=30,color='black', face="bold"),
        axis.line.y.left =element_line(color='black'),
        axis.text.y.left = element_text(size=30, color= 'black', face= 'bold'),
        axis.title.y.left = element_blank(),
        strip.background = element_blank(),
        strip.placement = "outside",
        strip.text = element_text(size = 30, color= 'black', face="bold"),
        plot.margin = unit(c(0,0.5,0.5,0), "cm"))


plot_alcohols_conc_chlorMax <- plot_grid(pBrass_chlorMax,pChol_chlorMax, pDip_chlorMax, pErgo_chlorMax, pSito_chlorMax, pStigma_chlorMax,
                                         pPhytol_chlorMax, ncol=1, align="v", 
                                         rel_heights = c(1.6,1,1,1,1,1,1.125), axis='lr')


FigS9 <- plot_grid(plot_alcohols_conc_surface, plot_alcohols_conc_chlorMax, ncol=2,rel_widths = c(1.1,1), align="h")

```

## Fig. S9

```{r, fig.width = 22.5, fig.height = 17.5, echo=FALSE}

plot(FigS9)

```
## Fatty acid concentrations water column

```{r}

#surface water

C14.0_A <- melt(subset(lipid_conc_surface, select= c(date,C14.0_ugL)),id.var="date")

C16.0_A <- melt(subset(lipid_conc_surface, select= c(date,C16.0_ugL)),id.var="date")

C16.1_A <- melt(subset(lipid_conc_surface, select= c(date,C16.1_ugL)),id.var="date")

C18.0_A <- melt(subset(lipid_conc_surface, select= c(date,C18.0_ugL)),id.var="date")

C18.1_A <- melt(subset(lipid_conc_surface, select= c(date,C18.1_ugL)),id.var="date")

C18.x_A <- melt(subset(lipid_conc_surface, select= c(date,C18.x_ugL)),id.var="date")

C18.2_A <- melt(subset(lipid_conc_surface, select= c(date,C18.2_ugL)),id.var="date")

C18.3nx_A <- melt(subset(lipid_conc_surface, select= c(date,C18.3nx_ugL)),id.var="date")

C20.3nx_A <- melt(subset(lipid_conc_surface, select= c(date,C20.3nx_ugL)),id.var="date")

C20.4_A <- melt(subset(lipid_conc_surface, select= c(date,C20.4_ugL)),id.var="date")

C22.2_A <- melt(subset(lipid_conc_surface, select= c(date,C22.2_ugL)),id.var="date")

C22.6_A <- melt(subset(lipid_conc_surface, select= c(date,C22.6_ugL)),id.var="date")


#chlorophyll maximum depth


C14.0_B <- melt(subset(lipid_conc_chlorMax, select= c(date,C14.0_ugL)),id.var="date")

C16.0_B <- melt(subset(lipid_conc_chlorMax, select= c(date,C16.0_ugL)),id.var="date")

C16.1_B <- melt(subset(lipid_conc_chlorMax, select= c(date,C16.1_ugL)),id.var="date")

C18.0_B <- melt(subset(lipid_conc_chlorMax, select= c(date,C18.0_ugL)),id.var="date")

C18.1_B <- melt(subset(lipid_conc_chlorMax, select= c(date,C18.1_ugL)),id.var="date")

C18.x_B <- melt(subset(lipid_conc_chlorMax, select= c(date,C18.x_ugL)),id.var="date")

C18.2_B <- melt(subset(lipid_conc_chlorMax, select= c(date,C18.2_ugL)),id.var="date")

C18.3nx_B <- melt(subset(lipid_conc_chlorMax, select= c(date,C18.3nx_ugL)),id.var="date")

C20.3nx_B <- melt(subset(lipid_conc_chlorMax, select= c(date,C20.3nx_ugL)),id.var="date")

C20.4_B <- melt(subset(lipid_conc_chlorMax, select= c(date,C20.4_ugL)),id.var="date")

C22.2_B <- melt(subset(lipid_conc_chlorMax, select= c(date,C22.2_ugL)),id.var="date")

C22.6_B <- melt(subset(lipid_conc_chlorMax, select= c(date,C22.6_ugL)),id.var="date")

```

## plotting fatty acid concentrations

```{r}
#surface water

pC14.0_surface <- ggplot() + 
  ggtitle("1 m depth", subtitle= "1 m depth")+
  geom_point(data=C14.0_A, aes(x=date,y=value), fill= "black", shape= 23, size=3,alpha=0.8)+
  geom_line(data=C14.0_A, aes(x=date,y=value),color= "black",  linewidth= 1)+ 
  annotate("text",y= 22, x= as.Date("2018-11-30"),label="A", size=15, fontface=2, color="black")+
  coord_cartesian(ylim=c(0,15),x=as.Date(c("2019-01-30", "2020-02-06")), clip="off")+
  scale_y_continuous(breaks=c(0.0,5.0,10.0,15.0))+
  ylab(expression(atop("C14:0","[µg/L]"))) + xlab(NULL)+
  theme(axis.line = element_line(colour = "black"),
        plot.title= element_text(size=35, face= "bold"),
        plot.subtitle= element_text(size=15, color="white"),
        panel.background = element_blank(),
        axis.line.x =element_blank(),
        axis.ticks.x = element_blank(),
        axis.text.x = element_blank(),
        axis.text.y = element_text(size=30,color='black', face="bold"),
        axis.title.y = element_text(size=30,color='black', face="bold"),
        legend.position = "none",
        strip.background = element_blank(),
        strip.placement = "outside",
        strip.text = element_text(size = 30, color= 'black', face="bold"),
        plot.margin = unit(c(1,0,0.5,0.5), "cm"))


pC16.0_surface <- ggplot() + 
  geom_point(data=C16.0_A, aes(x=date,y=value), fill= "black", shape= 23, size=3,alpha=0.8)+
  geom_line(data=C16.0_A, aes(x=date,y=value),color= "black",  linewidth= 1)+ 
  coord_cartesian(ylim=c(0,15),x=as.Date(c("2019-01-30", "2020-02-06")), clip="off")+
  ylab(expression(atop("C16:0","[µg/L]"))) + xlab(NULL)+
  scale_y_continuous(breaks=c(0.0,5.0,10.0,15.0))+
  theme(axis.line = element_line(colour = "black"),
        panel.background = element_blank(),
        axis.line.x =element_blank(),
        axis.ticks.x = element_blank(),
        axis.text.x = element_blank(),
        axis.text.y = element_text(size=30,color='black', face="bold"),
        axis.title.y = element_text(size=30,color='black', face="bold"),
        legend.position = "none",
        strip.background = element_blank(),
        strip.placement = "outside",
        strip.text = element_text(size = 30, color= 'black', face="bold"),
        plot.margin = unit(c(0,0,0.5,0.5), "cm"))


pC16.1_surface <- ggplot() + 
  geom_point(data=C16.1_A, aes(x=date,y=value), fill= "black", shape= 23, size=3,alpha=0.8)+
  geom_line(data=C16.1_A, aes(x=date,y=value),color= "black",  linewidth= 1)+ 
  coord_cartesian(ylim=c(0,25),x=as.Date(c("2019-01-30", "2020-02-06")), clip="off")+
  ylab(expression(atop("C16:1","[µg/L]"))) + xlab(NULL)+
  scale_y_continuous(breaks=c(0.0,12.5,25.0))+
  theme(axis.line = element_line(colour = "black"),
        panel.background = element_blank(),
        axis.line.x =element_blank(),
        axis.ticks.x = element_blank(),
        axis.text.x = element_blank(),
        axis.text.y = element_text(size=30,color='black', face="bold"),
        axis.title.y = element_text(size=30,color='black', face="bold"),
        legend.position = "none",
        strip.background = element_blank(),
        strip.placement = "outside",
        strip.text = element_text(size = 30, color= 'black', face="bold"),
        plot.margin = unit(c(0,0,0.5,0.5), "cm"))


pC18.0_surface <- ggplot() + 
  geom_point(data=C18.0_A, aes(x=date,y=value), fill= "black", shape= 23, size=3,alpha=0.8)+
  geom_line(data=C18.0_A, aes(x=date,y=value),color= "black",  linewidth= 1)+ 
  coord_cartesian(ylim=c(0,5),x=as.Date(c("2019-01-30", "2020-02-06")), clip="off")+
  ylab(expression(atop("C18:0","[µg/L]"))) + xlab(NULL)+
  scale_y_continuous(breaks=c(0.0, 2.5, 5.0))+
  theme(axis.line = element_line(colour = "black"),
        panel.background = element_blank(),
        axis.line.x =element_blank(),
        axis.ticks.x = element_blank(),
        axis.text.x = element_blank(),
        axis.text.y = element_text(size=30,color='black', face="bold"),
        axis.title.y = element_text(size=30,color='black', face="bold"),
        legend.position = "none",
        strip.background = element_blank(),
        strip.placement = "outside",
        strip.text = element_text(size = 30, color= 'black', face="bold"),
        plot.margin = unit(c(0,0,0.5,0.5), "cm"))


pC18.1_surface <- ggplot() + 
  geom_point(data=C18.1_A, aes(x=date,y=value), fill= "black", shape= 23, size=3,alpha=0.8)+
  geom_line(data=C18.1_A, aes(x=date,y=value),color= "black",  linewidth= 1)+ 
  coord_cartesian(ylim=c(0,20),x=as.Date(c("2019-01-30", "2020-02-06")), clip="off")+
  scale_y_continuous(breaks=c(0.0,10.0,20.0))+
  ylab(expression(atop("C18:1","[µg/L]"))) + xlab(NULL)+
  theme(axis.line = element_line(colour = "black"),
        panel.background = element_blank(),
        axis.line.x =element_blank(),
        axis.ticks.x = element_blank(),
        axis.text.x = element_blank(),
        axis.text.y = element_text(size=30,color='black', face="bold"),
        axis.title.y = element_text(size=30,color='black', face="bold"),
        legend.position = "none",
        strip.background = element_blank(),
        strip.placement = "outside",
        strip.text = element_text(size = 30, color= 'black', face="bold"),
        plot.margin = unit(c(0,0,0.5,0.5), "cm"))


pC18.x_surface <- ggplot() + 
  geom_point(data=C18.x_A, aes(x=date,y=value), fill= "black", shape= 23, size=3,alpha=0.8)+
  geom_line(data=C18.x_A, aes(x=date,y=value),color= "black",  linewidth= 1)+ 
  coord_cartesian(ylim=c(0,25),x=as.Date(c("2019-01-30", "2020-02-06")), clip="off")+
  scale_y_continuous(breaks=c(0.0,12.5,25.0))+
  ylab(expression(atop("C18:x","[µg/L]"))) + xlab(NULL)+
  theme(axis.line = element_line(colour = "black"),
        panel.background = element_blank(),
        axis.line.x =element_blank(),
        axis.ticks.x = element_blank(),
        axis.text.x = element_blank(),
        axis.text.y = element_text(size=30,color='black', face="bold"),
        axis.title.y = element_text(size=30,color='black', face="bold"),
        legend.position = "none",
        strip.background = element_blank(),
        strip.placement = "outside",
        strip.text = element_text(size = 30, color= 'black', face="bold"),
        plot.margin = unit(c(0,0,0.5,0.5), "cm"))


pC18.2_surface <- ggplot() + 
  geom_point(data=C18.2_A, aes(x=date,y=value), fill= "black", shape= 23, size=3,alpha=0.8)+
  geom_line(data=C18.2_A, aes(x=date,y=value),color= "black",  linewidth= 1)+ 
  coord_cartesian(ylim=c(0,10),x=as.Date(c("2019-01-30", "2020-02-06")), clip="off")+
  scale_y_continuous(breaks=c(0.0,5.0,10.0))+
  ylab(expression(atop("C18:2","[µg/L]"))) + xlab(NULL)+
  theme(axis.line = element_line(colour = "black"),
        panel.background = element_blank(),
        axis.line.x =element_blank(),
        axis.ticks.x = element_blank(),
        axis.text.x = element_blank(),
        axis.text.y = element_text(size=30,color='black', face="bold"),
        axis.title.y = element_text(size=30,color='black', face="bold"),
        legend.position = "none",
        strip.background = element_blank(),
        strip.placement = "outside",
        strip.text = element_text(size = 30, color= 'black', face="bold"),
        plot.margin = unit(c(0,0,0.5,0.5), "cm"))


pC18.3nx_surface <- ggplot() + 
  geom_point(data=C18.3nx_A, aes(x=date,y=value), fill= "black", shape= 23, size=3,alpha=0.8)+
  geom_line(data=C18.3nx_A, aes(x=date,y=value),color= "black",  linewidth= 1)+ 
  coord_cartesian(ylim=c(0,15),x=as.Date(c("2019-01-30", "2020-02-06")), clip="off")+
  scale_y_continuous(breaks=c(0.0,5.0,10.0,15.0))+
  ylab(expression(atop("C18:3nx","[µg/L]"))) + xlab(NULL)+
  theme(axis.line = element_line(colour = "black"),
        panel.background = element_blank(),
        axis.line.x =element_blank(),
        axis.ticks.x = element_blank(),
        axis.text.x = element_blank(),
        axis.text.y = element_text(size=30,color='black', face="bold"),
        axis.title.y = element_text(size=30,color='black', face="bold"),
        legend.position = "none",
        strip.background = element_blank(),
        strip.placement = "outside",
        strip.text = element_text(size = 30, color= 'black', face="bold"),
        plot.margin = unit(c(0,0,0.5,0.5), "cm"))


pC20.3nx_surface <- ggplot() + 
  geom_point(data=C20.3nx_A, aes(x=date,y=value), fill= "black", shape= 23, size=3,alpha=0.8)+
  geom_line(data=C20.3nx_A, aes(x=date,y=value),color= "black",  linewidth= 1)+ 
  coord_cartesian(ylim=c(0,1.5),x=as.Date(c("2019-01-30", "2020-02-06")), clip="off")+
  scale_y_continuous(breaks=c(0.0,0.5,1,1.5))+
  ylab(expression(atop("C20:3nx","[µg/L]"))) + xlab(NULL)+
  theme(axis.line = element_line(colour = "black"),
        panel.background = element_blank(),
        axis.line.x =element_blank(),
        axis.ticks.x = element_blank(),
        axis.text.x = element_blank(),
        axis.text.y = element_text(size=30,color='black', face="bold"),
        axis.title.y = element_text(size=30,color='black', face="bold"),
        legend.position = "none",
        strip.background = element_blank(),
        strip.placement = "outside",
        strip.text = element_text(size = 30, color= 'black', face="bold"),
        plot.margin = unit(c(0,0,0.5,0.5), "cm"))



pC20.4_surface <- ggplot() + 
  geom_point(data=C20.4_A, aes(x=date,y=value), fill= "black", shape= 23, size=3,alpha=0.8)+
  geom_line(data=C20.4_A, aes(x=date,y=value),color= "black",  linewidth= 1)+ 
  coord_cartesian(ylim=c(0,10),x=as.Date(c("2019-01-30", "2020-02-06")), clip="off")+
  scale_y_continuous(breaks=c(0.0,5.0,10.0))+
  ylab(expression(atop("C20:4","[µg/L]"))) + xlab(NULL)+
  theme(axis.line = element_line(colour = "black"),
        panel.background = element_blank(),
        axis.line.x =element_blank(),
        axis.ticks.x = element_blank(),
        axis.text.x = element_blank(),
        axis.text.y = element_text(size=30,color='black', face="bold"),
        axis.title.y = element_text(size=30,color='black', face="bold"),
        legend.position = "none",
        strip.background = element_blank(),
        strip.placement = "outside",
        strip.text = element_text(size = 30, color= 'black', face="bold"),
        plot.margin = unit(c(0,0,0.5,0.5), "cm"))



pC22.2_surface <- ggplot() + 
  geom_point(data=C22.2_A, aes(x=date,y=value), fill= "black", shape= 23, size=3,alpha=0.8)+
  geom_line(data=C22.2_A, aes(x=date,y=value),color= "black",  linewidth= 1)+ 
  coord_cartesian(ylim=c(0,1.5),x=as.Date(c("2019-01-30", "2020-02-06")), clip="off")+
  scale_y_continuous(breaks=c(0.0,0.5,1,1.5))+
  ylab(expression(atop("C22:2","[µg/L]"))) + xlab(NULL)+
  theme(axis.line = element_line(colour = "black"),
        panel.background = element_blank(),
        axis.line.x =element_blank(),
        axis.ticks.x = element_blank(),
        axis.text.x = element_blank(),
        axis.text.y = element_text(size=30,color='black', face="bold"),
        axis.title.y = element_text(size=30,color='black', face="bold"),
        legend.position = "none",
        strip.background = element_blank(),
        strip.placement = "outside",
        strip.text = element_text(size = 30, color= 'black', face="bold"),
        plot.margin = unit(c(0,0,0.5,0.5), "cm"))


pC22.6_surface <- ggplot() + 
  geom_point(data=C22.6_A, aes(x=date,y=value), fill= "black", shape= 23, size=3,alpha=0.8)+
  geom_line(data=C22.6_A, aes(x=date,y=value),color= "black",  linewidth= 1)+ 
  coord_cartesian(ylim=c(0,5),x=as.Date(c("2019-01-30", "2020-02-06")), clip="off")+
  scale_y_continuous(breaks=c(0.0,2.5,5.0))+
  ylab(expression(atop("C22:6","[µg/L]"))) + xlab(NULL)+
  theme(axis.line = element_line(colour = "black"),
        panel.background = element_blank(),
        axis.line.x =element_line(color="black"),
        axis.text.x = element_text(size=30,color='black', face="bold"),
        axis.line.y.left =element_line(color='black'),
        axis.text.y.left = element_text(size=30, color= 'black', face= 'bold'),
        axis.title.y.left = element_text(size=30, color= 'black', face= 'bold'),
        strip.background = element_blank(),
        strip.placement = "outside",
        strip.text = element_text(size = 30, color= 'black', face="bold"),
        plot.margin = unit(c(0,0,0.5,0.5), "cm"))



plot_FA_conc_surface <- plot_grid(pC14.0_surface,pC16.0_surface, pC16.1_surface, pC18.0_surface, pC18.1_surface,
                                  pC18.x_surface, pC18.2_surface, pC18.3nx_surface,pC20.3nx_surface, pC20.4_surface,
                                  pC22.2_surface, pC22.6_surface, ncol=1, align="v", 
                                  rel_heights = c(1.45,1,1,1,1,1,1,1,1,1,1,1.15), axis='lr')


#chlorophyll maximum depth

pC14.0_chlorMax <- ggplot() + 
  ggtitle("chlorophyll maximum depth", subtitle= "chlorophyll maximum depth")+
  geom_point(data=C14.0_B, aes(x=date,y=value, fill=variable), shape= 23, size=3,alpha=0.8)+
  geom_line(data=C14.0_B, aes(x=date,y=value),color= "black",  linewidth= 1)+ 
  scale_fill_manual(labels=c("C14.0_ugL"= "C14:0 [µg/L]"),
                    values=c(C14.0_ugL="black"))+
  annotate("text",y= 22, x= as.Date("2018-11-30"),label="B", size=15, fontface=2, color="black")+
  coord_cartesian(ylim=c(0,15),x=as.Date(c("2019-01-30", "2020-02-06")), clip="off")+
  scale_y_continuous(breaks=c(0.0,5.0,10.0,15.0))+
  ylab("C14:0 [µg/L]") + xlab(NULL)+
  theme(axis.line = element_line(colour = "black"),
        legend.position = "none",
        plot.title= element_text(size=35, face= "bold"),
        plot.subtitle= element_text(size=15, color="white"),
        panel.background = element_blank(),
        axis.line.x =element_blank(),
        axis.ticks.x = element_blank(),
        axis.text.x = element_blank(),
        axis.text.y = element_text(size=30,color='black', face="bold"),
        axis.title.y = element_blank(),
        strip.background = element_blank(),
        strip.placement = "outside",
        strip.text = element_text(size = 30, color= 'black', face="bold"),
        plot.margin = unit(c(1,0.5,0.5,0), "cm"))



pC16.0_chlorMax <- ggplot() + 
  geom_point(data=C16.0_B, aes(x=date,y=value, fill= variable), shape= 23, size=3,alpha=0.8)+
  geom_line(data=C16.0_B, aes(x=date,y=value),color= "black",  linewidth= 1)+ 
  scale_fill_manual(labels=c("C16.0_ugL"= "C16:0 [µg/L]"),
                    values=c(C16.0_ugL="black"))+
  coord_cartesian(ylim=c(0,15),x=as.Date(c("2019-01-30", "2020-02-06")), clip="off")+
  scale_y_continuous(breaks=c(0.0,5.0,10.0,15.0))+
  ylab("C16:0 [µg/L]") + xlab(NULL)+
  theme(axis.line = element_line(colour = "black"),
        panel.background = element_blank(),
        legend.position = "none",
        axis.line.x =element_blank(),
        axis.ticks.x = element_blank(),
        axis.text.x = element_blank(),
        axis.text.y = element_text(size=30,color='black', face="bold"),
        axis.title.y = element_blank(),
        strip.background = element_blank(),
        strip.placement = "outside",
        strip.text = element_text(size = 30, color= 'black', face="bold"),
        plot.margin = unit(c(0,0.5,0.5,0), "cm"))



pC16.1_chlorMax <- ggplot() + 
  geom_point(data=C16.1_B, aes(x=date,y=value, fill= variable), shape= 23, size=3,alpha=0.8)+
  geom_line(data=C16.1_B, aes(x=date,y=value),color= "black",  linewidth= 1)+ 
  scale_fill_manual(labels=c("C16.1_ugL"= "C16:1 [µg/L]"),
                    values=c(C16.1_ugL="black"))+
  coord_cartesian(ylim=c(0,25),x=as.Date(c("2019-01-30", "2020-02-06")), clip="off")+
  scale_y_continuous(breaks=c(0.0,12.5,25.0))+
  ylab("C16:1 [µg/L]") + xlab(NULL)+
  theme(axis.line = element_line(colour = "black"),
        legend.position = "none",
        panel.background = element_blank(),
        axis.line.x =element_blank(),
        axis.ticks.x = element_blank(),
        axis.text.x = element_blank(),
        axis.text.y = element_text(size=30,color='black', face="bold"),
        axis.title.y = element_blank(),
        strip.background = element_blank(),
        strip.placement = "outside",
        strip.text = element_text(size = 30, color= 'black', face="bold"),
        plot.margin = unit(c(0,0.5,0.5,0), "cm"))


pC18.0_chlorMax <- ggplot() + 
  geom_point(data=C18.0_B, aes(x=date,y=value, fill= variable), shape= 23, size=3,alpha=0.8)+
  geom_line(data=C18.0_B, aes(x=date,y=value),color= "black",  linewidth= 1)+ 
  scale_fill_manual(labels=c("C18.0_ugL"= "C18:0 [µg/L]"),
                    values=c(C18.0_ugL="black"))+
  coord_cartesian(ylim=c(0,5),x=as.Date(c("2019-01-30", "2020-02-06")), clip="off")+
  scale_y_continuous(breaks=c(0.0,2.5,5.0))+
  ylab("C18:0 [µg/L]") + xlab(NULL)+
  theme(axis.line = element_line(colour = "black"),
        legend.position = "none",
        panel.background = element_blank(),
        axis.line.x =element_blank(),
        axis.ticks.x = element_blank(),
        axis.text.x = element_blank(),
        axis.text.y = element_text(size=30,color='black', face="bold"),
        axis.title.y = element_blank(),
        strip.background = element_blank(),
        strip.placement = "outside",
        strip.text = element_text(size = 30, color= 'black', face="bold"),
        plot.margin = unit(c(0,0.5,0.5,0), "cm"))


pC18.1_chlorMax <- ggplot() + 
  geom_point(data=C18.1_B, aes(x=date,y=value, fill= variable), shape= 23, size=3,alpha=0.8)+
  geom_line(data=C18.1_B, aes(x=date,y=value),color= "black",  linewidth= 1)+ 
  scale_fill_manual(labels=c("C18.1_ugL"= "C18:1 [µg/L]"),
                    values=c(C18.1_ugL="black"))+
  coord_cartesian(ylim=c(0,20),x=as.Date(c("2019-01-30", "2020-02-06")), clip="off")+
  scale_y_continuous(breaks=c(0.0,10.0,20.0))+
  ylab("C18:1 [µg/L]") + xlab(NULL)+
  theme(axis.line = element_line(colour = "black"),
        legend.position = "none",
        panel.background = element_blank(),
        axis.line.x =element_blank(),
        axis.ticks.x = element_blank(),
        axis.text.x = element_blank(),
        axis.text.y = element_text(size=30,color='black', face="bold"),
        axis.title.y = element_blank(),
        strip.background = element_blank(),
        strip.placement = "outside",
        strip.text = element_text(size = 30, color= 'black', face="bold"),
        plot.margin = unit(c(0,0.5,0.5,0), "cm"))


pC18.x_chlorMax <- ggplot() + 
  geom_point(data=C18.x_B, aes(x=date,y=value, fill= variable), shape= 23, size=3,alpha=0.8)+
  geom_line(data=C18.x_B, aes(x=date,y=value),color= "black",  linewidth= 1)+ 
  scale_fill_manual(labels=c("C18.x_ugL"= "C18:x [µg/L]"),
                    values=c(C18.x_ugL="black"))+
  coord_cartesian(ylim=c(0,25),x=as.Date(c("2019-01-30", "2020-02-06")), clip="off")+
  scale_y_continuous(breaks=c(0.0,12.5,25.0))+
  ylab("C18:x [µg/L]") + xlab(NULL)+
  theme(axis.line = element_line(colour = "black"),
        legend.position = "none",
        panel.background = element_blank(),
        axis.line.x =element_blank(),
        axis.ticks.x = element_blank(),
        axis.text.x = element_blank(),
        axis.text.y = element_text(size=30,color='black', face="bold"),
        axis.title.y = element_blank(),
        strip.background = element_blank(),
        strip.placement = "outside",
        strip.text = element_text(size = 30, color= 'black', face="bold"),
        plot.margin = unit(c(0,0.5,0.5,0), "cm"))


pC18.2_chlorMax <- ggplot() + 
  geom_point(data=C18.2_B, aes(x=date,y=value, fill= variable), shape= 23, size=3,alpha=0.8)+
  geom_line(data=C18.2_B, aes(x=date,y=value),color= "black",  linewidth= 1)+ 
  scale_fill_manual(labels=c("C18.2_ugL"= "C18:2 [µg/L]"),
                    values=c(C18.2_ugL="black"))+
  coord_cartesian(ylim=c(0,10),x=as.Date(c("2019-01-30", "2020-02-06")), clip="off")+
  scale_y_continuous(breaks=c(0.0,5.0,10.0))+
  ylab("C18:2 [µg/L]") + xlab(NULL)+
  theme(axis.line = element_line(colour = "black"),
        legend.position = "none",
        panel.background = element_blank(),
        axis.line.x =element_blank(),
        axis.ticks.x = element_blank(),
        axis.text.x = element_blank(),
        axis.text.y = element_text(size=30,color='black', face="bold"),
        axis.title.y = element_blank(),
        strip.background = element_blank(),
        strip.placement = "outside",
        strip.text = element_text(size = 30, color= 'black', face="bold"),
        plot.margin = unit(c(0,0.5,0.5,0), "cm"))


pC18.3nx_chlorMax <- ggplot() + 
  geom_point(data=C18.3nx_B, aes(x=date,y=value, fill= variable), shape= 23, size=3,alpha=0.8)+
  geom_line(data=C18.3nx_B, aes(x=date,y=value),color= "black",  linewidth= 1)+ 
  scale_fill_manual(labels=c("C18.3nx_ugL"= "C18:3nx [µg/L]"),
                    values=c(C18.3nx_ugL="black"))+
  coord_cartesian(ylim=c(0,15),x=as.Date(c("2019-01-30", "2020-02-06")), clip="off")+
  scale_y_continuous(breaks=c(0.0,5.0,10.0,15.0))+
  ylab("C18:3nx [µg/L]") + xlab(NULL)+
  theme(axis.line = element_line(colour = "black"),
        legend.position = "none",
        panel.background = element_blank(),
        axis.line.x =element_blank(),
        axis.ticks.x = element_blank(),
        axis.text.x = element_blank(),
        axis.text.y = element_text(size=30,color='black', face="bold"),
        axis.title.y = element_blank(),
        strip.background = element_blank(),
        strip.placement = "outside",
        strip.text = element_text(size = 30, color= 'black', face="bold"),
        plot.margin = unit(c(0,0.5,0.5,0), "cm"))



pC20.3nx_chlorMax <- ggplot() + 
  geom_point(data=C20.3nx_B, aes(x=date,y=value, fill= variable), shape= 23, size=3,alpha=0.8)+
  geom_line(data=C20.3nx_B, aes(x=date,y=value),color= "black",  linewidth= 1)+ 
  scale_fill_manual(labels=c("C20.3nx_ugL"= "C20:3nx [µg/L]"),
                    values=c(C20.3nx_ugL="black"))+
  coord_cartesian(ylim=c(0,1.5),x=as.Date(c("2019-01-30", "2020-02-06")), clip="off")+
  scale_y_continuous(breaks=c(0.0,0.5,1,1.5))+
  ylab("C20.3nx [µg/L]") + xlab(NULL)+
  theme(axis.line = element_line(colour = "black"),
        legend.position = "none",
        panel.background = element_blank(),
        axis.line.x =element_blank(),
        axis.ticks.x = element_blank(),
        axis.text.x = element_blank(),
        axis.text.y = element_text(size=30,color='black', face="bold"),
        axis.title.y = element_blank(),
        strip.background = element_blank(),
        strip.placement = "outside",
        strip.text = element_text(size = 30, color= 'black', face="bold"),
        plot.margin = unit(c(0,0.5,0.5,0), "cm"))



pC20.4_chlorMax <- ggplot() + 
  geom_point(data=C20.4_B, aes(x=date,y=value, fill=variable), shape= 23, size=3,alpha=0.8)+
  geom_line(data=C20.4_B, aes(x=date,y=value),color= "black",  linewidth= 1)+ 
  scale_fill_manual(labels=c("C20.4_ugL"= "C20:4 [µg/L]"),
                    values=c(C20.4_ugL="black"))+
  coord_cartesian(ylim=c(0,10),x=as.Date(c("2019-01-30", "2020-02-06")), clip="off")+
  scale_y_continuous(breaks=c(0.0,5.0,10.0))+
  ylab("C20.4 [µg/L]") + xlab(NULL)+
  theme(axis.line = element_line(colour = "black"),
        legend.position = "none",
        panel.background = element_blank(),
        axis.line.x =element_blank(),
        axis.ticks.x = element_blank(),
        axis.text.x = element_blank(),
        axis.text.y = element_text(size=30,color='black', face="bold"),
        axis.title.y =element_blank(),
        strip.background = element_blank(),
        strip.placement = "outside",
        strip.text = element_text(size = 30, color= 'black', face="bold"),
        plot.margin = unit(c(0,0.5,0.5,0), "cm"))



pC22.2_chlorMax <- ggplot() + 
  geom_point(data=C22.2_B, aes(x=date,y=value, fill= variable), shape= 23, size= 4,alpha=0.8)+
  geom_line(data=C22.2_B, aes(x=date,y=value),color= "black",  linewidth= 1)+ 
  scale_fill_manual(labels=c("C22.2_ugL"= "C22:2 [µg/L]"),
                    values=c(C22.2_ugL="black"))+
  coord_cartesian(ylim=c(0,1.5),x=as.Date(c("2019-01-30", "2020-02-06")), clip="off")+
  scale_y_continuous(breaks=c(0.0,0.5,1,1.5))+
  ylab("C22.2 [µg/L]") + xlab(NULL)+
  theme(axis.line = element_line(colour = "black"),
        legend.position = "none",
        panel.background = element_blank(),
        axis.line.x =element_blank(),
        axis.ticks.x = element_blank(),
        axis.text.x = element_blank(),
        axis.text.y = element_text(size=30,color='black', face="bold"),
        axis.title.y = element_blank(),
        strip.background = element_blank(),
        strip.placement = "outside",
        strip.text = element_text(size = 30, color= 'black', face="bold"),
        plot.margin = unit(c(0,0.5,0.5,0), "cm"))


pC22.6_chlorMax <- ggplot() + 
  geom_point(data=C22.6_B, aes(x=date,y=value, fill= variable), shape= 23, size=3,alpha=0.8)+
  geom_line(data=C22.6_B, aes(x=date,y=value),color= "black",  linewidth= 1)+ 
  scale_fill_manual(labels=c("C22.6_ugL"= "C22.6 [µg/L]"),
                    values=c(C22.6_ugL="black"))+
  coord_cartesian(ylim=c(0,5),x=as.Date(c("2019-01-30", "2020-02-06")), clip="off")+
  scale_y_continuous(breaks=c(0.0,2.5,5.0))+
  ylab("C22.6 [µg/L]") + xlab(NULL)+
  theme(axis.line = element_line(colour = "black"),
        legend.position = "none",
        panel.background = element_blank(),
        axis.line.x =element_line(color="black"),
        axis.text.x = element_text(size=30,color='black', face="bold"),
        axis.line.y.left =element_line(color='black'),
        axis.text.y.left = element_text(size=30, color= 'black', face= 'bold'),
        axis.title.y.left = element_blank(),
        strip.background = element_blank(),
        strip.placement = "outside",
        strip.text = element_text(size = 30, color= 'black', face="bold"),
        plot.margin = unit(c(0,0.5,0.5,0), "cm"))



plot_FA_conc_chlorMax <- plot_grid(pC14.0_chlorMax,pC16.0_chlorMax, pC16.1_chlorMax, pC18.0_chlorMax, pC18.1_chlorMax,
                                   pC18.x_chlorMax, pC18.2_chlorMax, pC18.3nx_chlorMax,pC20.3nx_chlorMax, pC20.4_chlorMax,
                                   pC22.2_chlorMax, pC22.6_chlorMax, ncol=1, align="v", 
                                   rel_heights = c(1.45,1,1,1,1,1,1,1,1,1,1,1.15), axis='lr')


FigS10 <- plot_grid(plot_FA_conc_surface, plot_FA_conc_chlorMax, ncol=2,rel_widths = c(1.05,1), align="h")

```

## Fig. S10

```{r, fig.width = 22.5, fig.height = 30, echo=FALSE}

plot(FigS10)

```


