---
title: "S12-TP-Temperature"
author: "Antonia_Klatt"
date: "2025-01-06"
output: html_document
---

```{r}
knitr::opts_chunk$set(echo = TRUE)

#loading packages
library(readr)
library(ggplot2)
library(reshape2)
library(cowplot)

Sys.setlocale("LC_ALL", "English")

TN_TP_Temp <- read.csv ("C:\\Users\\KlattA\\Desktop\\Uni Basel\\Basel AG Ladd\\PhD project\\PhD thesis\\Chapter 1 ROT19\\Supplementary_C1\\Tables_C1\\TN_TP_Temp_ROT19.csv", header = TRUE , sep = ";" , stringsAsFactors = FALSE, na.strings = "#NV")

#note: data frame includes two different depths: surface water (A) and chlorophyll maximum depth (B)

#separating surface water (surface) and chlorophyll maximum depth (chlorMax)

TN_TP_Temp_surface <- TN_TP_Temp[1:25,]

TN_TP_Temp_chlorMax <- TN_TP_Temp[26:49,]



#setting sampling dates

datesA <- c("2019-01-30","2019-02-13", "2019-02-27", "2019-03-13", "2019-03-27", "2019-04-10", "2019-04-24",
                       "2019-05-08", "2019-05-22", "2019-06-04", "2019-06-19", "2019-07-17", "2019-07-30", "2019-08-14",
                       "2019-09-11", "2019-09-25", "2019-10-09", "2019-10-23", "2019-11-06","2019-11-20", "2019-12-04",
                       "2019-12-18", "2020-01-07", "2020-01-21", "2020-02-06")

rownames(TN_TP_Temp_surface) <- datesA

TN_TP_Temp_surface$date <- as.Date(rownames(TN_TP_Temp_surface), "%Y-%m-%d")


datesB <- c("2019-01-30", "2019-02-13", "2019-03-13","2019-03-27", "2019-04-10", "2019-04-24", "2019-05-08",
                       "2019-05-22", "2019-06-04", "2019-06-19", "2019-07-17", "2019-07-30", "2019-08-14", "2019-09-11",
                       "2019-09-25", "2019-10-09", "2019-10-23", "2019-11-06","2019-11-20", "2019-12-04","2019-12-18",
                       "2020-01-07", "2020-01-21", "2020-02-06")

rownames(TN_TP_Temp_chlorMax) <- datesB

TN_TP_Temp_chlorMax$date <- as.Date(rownames(TN_TP_Temp_chlorMax), "%Y-%m-%d")


#reshape data frames

Temp_A <- melt(subset(TN_TP_Temp_surface, select= c(date,Temp_C)),id.var="date")

TP_A <- melt(subset(TN_TP_Temp_surface, select= c(date,Total_Phosphor_ugL)),id.var="date")


Temp_B <- melt(subset(TN_TP_Temp_chlorMax, select= c(date,Temp_C)),id.var="date")

TP_B <- melt(subset(TN_TP_Temp_chlorMax, select= c(date,Total_Phosphor_ugL)),id.var="date")

```

## plotting cyanobacterial biovolume, phytol:sterol ratios and C18:C16 ratios

```{r}

# surface water

TP_Temp_surface <- ggplot() + ggtitle("1 m depth", subtitle= "1 m depth")+
  geom_line(data= Temp_A[!is.na(Temp_A$value),], aes(x=date,y=value),color= "red3",  linewidth= 1.15)+ 
  geom_line(data= TP_A, aes(x=date,y=(value/2)),color= "slategray",  linewidth= 1.15)+ 
  scale_y_continuous("temperature (°C)", position = "left", sec.axis = dup_axis((~ .*2 ), name= "Total Phosphorus [µg/L]"))+
  annotate("text",y= 37, x= as.Date("2018-12-01"),label="A", size=15, fontface=2, color="black")+
  coord_cartesian(ylim=c(0,30),x=as.Date(c("2019-01-30", "2020-02-06")),clip="off")+
  xlab(NULL)+
  theme(axis.line = element_line(colour = "black"),
        plot.title= element_text(size=35, face= "bold"),
        plot.subtitle= element_text(size=30, color="white"),
        panel.background = element_blank(),
        axis.line.x =element_line(color="black"),
        axis.text.x = element_text(size=30,color='black', face="bold"),
        axis.text.y.left = element_text(size=30,color='red3', face="bold"),
        axis.title.y.left = element_text(size=30,color='red3', margin=margin(r=25)),
        axis.text.y.right = element_text(size=30,color='slategray', face="bold"),
        axis.title.y.right = element_blank(),
        #axis.line.y.right = element_blank(),
        #axis.ticks.y.right=element_blank(),
        legend.position = "none",
        strip.background = element_blank(),
        strip.placement = "outside",
        plot.margin = unit(c(1.35,0.25,0.5,1), "cm"))



#chlorophyll maximum depth

TP_Temp_chlorMax <- ggplot() + ggtitle("chlorophyll maximum depth", subtitle= "chlorophyll maximum depth")+
  geom_line(data= Temp_B[!is.na(Temp_B$value),], aes(x=date,y=value),color= "red3",  linewidth= 1.15)+ 
  geom_line(data= TP_B, aes(x=date,y=(value/2)),color= "slategray",  linewidth= 1.15)+ 
  scale_y_continuous("temperature (°C)", position = "left", sec.axis = dup_axis((~ .*2 ), name= "Total Phosphorus [µg/L]"))+
  annotate("text",y= 37, x= as.Date("2018-12-15"),label="B", size=15, fontface=2, color="black")+
  coord_cartesian(ylim=c(0,30),x=as.Date(c("2019-01-30", "2020-02-06")),clip="off")+
  xlab(NULL)+
  theme(axis.line = element_line(colour = "black"),
        plot.title= element_text(size=35, face= "bold"),
        plot.subtitle= element_text(size=30, color="white"),
        panel.background = element_blank(),
        axis.line.x =element_line(color="black"),
        axis.text.x = element_text(size=30,color='black', face="bold"),
        axis.text.y.left = element_text(size=30,color='red3', face="bold"),
        axis.title.y.left = element_blank(),
        #axis.line.y.left=element_blank(),
        #axis.ticks.y.left=element_blank(),
        axis.text.y.right = element_text(size=30,color='slategray', face="bold"),
        axis.title.y.right = element_text(size=30,color='slategray', margin=margin(l=25)),
        legend.position = "none",
        strip.background = element_blank(),
        strip.placement = "outside",
        plot.margin = unit(c(1.25,1,0.5,0.5), "cm"))

FigS12 <- plot_grid(TP_Temp_surface, TP_Temp_chlorMax, ncol=2,rel_widths = c(1,1.05), align="h")

```

## Fig. S12

```{r, fig.width = 25, fig.height = 7.5, echo=FALSE}

plot(FigS12)

```
